repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
  - repo: "https://github.com/macisamuele/language-formatters-pre-commit-hooks"
    rev: v2.10.0
    hooks:
      - id: pretty-format-toml
        args: ["--autofix"]
  - repo: "https://github.com/psf/black"
    rev: 23.7.0
    hooks:
      - id: black
  - repo: "https://github.com/PyCQA/flake8"
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--ignore=E203,E501,W503"]
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v1.4.1
    hooks:
      - id: mypy
