default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
    - id: requirements-updater
      name: requirements-dev updater
      entry: bash scripts/update_requirements.sh
      language: system
      stages: [pre-push]