[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cookiecutter-pyaction"
version = "0.1.0"
authors = [{ name = "Sadra Yahyapour", email = "lnxpylnxpy@gmail.com" }]
description = "A cookiecutter template for python-based custom github actions"
license = { file = "LICENSE" }
keywords = [
    "cookiecutter",
    "template",
    "github",
    "github-actions",
    "actions",
    "cicd",
]
readme = "README.md"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["bump2version", "cookiecutter", "pre-commit", "pytest", "tox"]
