[tool.poetry]
name = "cookiecutter-pyaction"
version = "0.1.0"
description = "A cookiecutter template for python-based custom github actions"
authors = ["Sadra Yahyapour <lnxpylnxpy@gmail.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
bumpversion = "^0.6.0"
cookiecutter = "^2.2.3"
pre-commit = "^3.3.3"
pytest = "^7.4.0"
tox = "^4.6.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
